# -*- coding: utf-8 -*-
"""Flask_App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqIlEO2iPSo5fFegg_9dt2gR7SPxejC3
"""

!pip install pymongo
!pip install pyngrok
from flask import Flask, render_template, request, redirect
from pymongo import MongoClient
import csv
from pyngrok import ngrok, conf

app = Flask(__name__)

# MongoDB connection
client = MongoClient('mongodb://localhost:27017/')
db = client["survey_db"]
collection = db["users"]

class User:
  def __init__(self, age, gender, income, expenses):
    self.age = age
    self.gender = gender
    self.income = income
    self.expenses = expenses

@app.route('/')
def index():
  return render_template('index.html')

@app.route('/submit', methods=['POST'])
def submit():
  age = request.form['age']
  gender = request.form['gender']
  income = request.form['income']

  expenses = {
      "utilities": request.form.get('utilities', 0),
      "entertainment": request.form.get('entertainment'),
      "school_fees": request.form.get('school_fees', 0),
      "shopping": request.form.get('shopping', 0),
      "healthcare": request.form.get('healthcare', 0),
      "transportation": request.form.get('transportation', 0),
  }

  user = User(age, gender, income, expenses)

  # Save to MongoDB
  collection.insert_one({
      "age": user.age,
      "gender": user.gender,
      "income": user.income,
      "expenses": user.expenses

  })

  return redirect('/')

@app.route('/export')
def export():
  users = list(collection.find())

  with open('data/users.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow([
        "Age", "Gender", "Income",
        "Utilities", "Entertainment",
        "School Fees", "Shopping", "Healthcare"
    ])

    for user in users:
      writer.writerow([
          user["age"],
          user["gender"],
          user["income"],
          user["expenses"].get("utilities", 0),
          user["expenses"].get("entertainment", 0),
          user["expenses"].get("school_fees", 0),
          user["expenses"].get("shopping", 0),
          user["expenses"].get("healthcare", 0)
        ])

  return "CSV Exported Successfully!"

if __name__ == '__main__':
  # Add your ngrok authtoken here
  # ngrok.set_auth_token("YOUR_AUTHTOKEN") # Uncomment and replace with your actual authtoken

  # Check if ngrok authtoken is set
  if not conf.get_default().auth_token:
      print("Please set your ngrok authtoken to proceed. Visit https://dashboard.ngrok.com/get-started/your-authtoken")
  else:
      public_url = ngrok.connect(5000)
      print("👉 Open this link in your browser:", public_url)

      app.run(port=5000, use_reloader=False)

import os

# Create templates folder if it doesn't exist
os.makedirs("templates", exist_ok=True)

html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Survey Form</title>
</head>
<body>
    <h2>User Survey</h2>
    <form action="/submit" method="POST">
        Age: <input type="number" name="age" required><br><br>
        Gender:
        <select name="gender">
            <option>Male</option>
            <option>Female</option>
        </select><br><br>
        Income: <input type="number" name="income" required><br><br>
        <h3>Expenses</h3>
        Utilities: <input type="number" name="utilities"><br>
        Entertainment: <input type="number" name="entertainment"><br>
        School Fees: <input type="number" name="school_fees"><br>
        Shopping: <input type="number" name="shopping"><br>
        Healthcare: <input type="number" name="healthcare"><br><br>
        <button type="submit">Submit</button>
    </form>
    <br>
    <a href="/export">Export CSV</a>
</body>
</html>
"""

# Save it inside templates folder
with open("templates/index.html", "w") as f:
    f.write(html_content)

from flask import Flask, render_template, request, redirect
import csv
import os

app = Flask(__name__)

# Route for main page
@app.route('/')
def index():
    return render_template('index.html')

# Route for form submission
@app.route('/submit', methods=['POST'])
def submit():
    # Get form data
    age = request.form.get('age')
    gender = request.form.get('gender')
    income = request.form.get('income')
    utilities = request.form.get('utilities')
    entertainment = request.form.get('entertainment')
    school_fees = request.form.get('school_fees')
    shopping = request.form.get('shopping')
    healthcare = request.form.get('healthcare')

    # Save to CSV
    file_exists = os.path.isfile('users.csv')
    with open('users.csv', 'a', newline='') as csvfile:
        writer = csv.writer(csvfile)
        # write header only if file is new
        if not file_exists:
            writer.writerow(['Age','Gender','Income','Utilities','Entertainment','School Fees','Shopping','Healthcare'])
        writer.writerow([age,gender,income,utilities,entertainment,school_fees,shopping,healthcare])

    return "Data submitted successfully!"

import requests
import random

url = "https://pilgrimatical-avery-inducible.ngrok-free.dev/submit"

# Send 20 random users
for _ in range(20):
    data = {
        "age": random.randint(18, 60),
        "gender": random.choice(["Male", "Female"]),
        "income": random.randint(30000, 150000),
        "utilities": random.randint(1000, 20000),
        "entertainment": random.randint(0, 10000),
        "school_fees": random.randint(0, 20000),
        "shopping": random.randint(0, 15000),
        "healthcare": random.randint(0, 15000)
    }

    response = requests.post(url, data=data)
    print(response.text)  # Should print "Data submitted successfully!"